plugins {
	id 'java'
	id 'io.github.kotlinmania.spring.boot. version '{version-spring-boot}'
}

// tag::configure-bom[]
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
	imports {
		mavenBom io.github.kotlinmania.spring.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
	}
}
// end::configure-bom[]

dependencyManagement {
	resolutionStrategy {
		eachDependency {
			if (it.requested.group == 'io.github.kotlinmania.spring.boot.) {
				it.useVersion 'TEST-SNAPSHOT'
			}
		}
	}
}

repositories {
	maven {
		url = 'repository'
	}
}
