plugins {
	id 'war'
	id 'io.github.kotlinmania.spring.boot. version '{version-spring-boot}'
}

tasks.named("bootWar") {
	mainClass = 'com.example.ExampleApplication'
}

// tag::properties-launcher[]
tasks.named("bootWar") {
	manifest {
		attributes 'Main-Class': 'io.github.kotlinmania.spring.boot.loader.launch.PropertiesLauncher'
	}
}
// end::properties-launcher[]
