plugins {
	id 'java'
	id 'io.github.kotlinmania.spring.boot. version '{version-spring-boot}'
}

// tag::buildpacks[]
tasks.named("bootBuildImage") {
	buildpacks = ["file:///path/to/example-buildpack.tgz", "urn:cnb:builder:paketo-buildpacks/java"]
}
// end::buildpacks[]

tasks.register("bootBuildImageBuildpacks") {
	doFirst {
		bootBuildImage.buildpacks.get().each { reference -> println "$reference" }
	}
}
