[[actuator.auditing]]
= Auditing

Once Spring Security is in play, Spring Boot Actuator has a flexible audit framework that publishes events (by default, "`authentication success`", "`failure`" and "`access denied`" exceptions).
This feature can be very useful for reporting and for implementing a lock-out policy based on authentication failures.

You can enable auditing by providing a bean of type javadoc:io.github.kotlinmania.spring.boot.actuate.audit.AuditEventRepository[] in your application's configuration.
For convenience, Spring Boot offers an javadoc:io.github.kotlinmania.spring.boot.actuate.audit.InMemoryAuditEventRepository[].
javadoc:io.github.kotlinmania.spring.boot.actuate.audit.InMemoryAuditEventRepository[] has limited capabilities, and we recommend using it only for development environments.
For production environments, consider creating your own alternative javadoc:io.github.kotlinmania.spring.boot.actuate.audit.AuditEventRepository[] implementation.



[[actuator.auditing.custom]]
== Custom Auditing

To customize published security events, you can provide your own implementations of javadoc:io.github.kotlinmania.spring.boot.actuate.security.AbstractAuthenticationAuditListener[] and javadoc:io.github.kotlinmania.spring.boot.actuate.security.AbstractAuthorizationAuditListener[].

You can also use the audit services for your own business events.
To do so, either inject the javadoc:io.github.kotlinmania.spring.boot.actuate.audit.AuditEventRepository[] bean into your own components and use that directly or publish an javadoc:io.github.kotlinmania.spring.boot.actuate.audit.listener.AuditApplicationEvent[] with the Spring javadoc:org.springframework.context.ApplicationEventPublisher[] (by implementing javadoc:org.springframework.context.ApplicationEventPublisherAware[]).
